/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.io.grpc.grpc.netty.shaded)
    api(libs.io.grpc.grpc.protobuf)
    api(libs.io.grpc.grpc.stub)
    api(libs.com.google.protobuf.protobuf.java)
    api(libs.javax.annotation.javax.annotation.api)
    testImplementation(libs.junit.junit)
}

group = "com.example"
version = "1.0-SNAPSHOT"
description = "demo"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
